name: Daily Code Execution

on:
  schedule:
    - cron: '0 0 * * *'
  
  push:
    # Optionally specify branches if needed
    branches:
      - main  # Change 'master' to the default branch of your repository if it's different

permissions:
  contents: write    # cho ph√©p push changes back to repo

jobs:
  execute-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for Google API
        run: |
          pip install -r requirements.txt

      - name: Execute script
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          python -m src.main

      - name: Configure Git
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      - name: Add changes to git
        run: |
          git add README.md ./data

      - name: Commit changes
        run: |
          git commit -m "Daily Code Execution GitHub Action" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main